Fix error in docker-compose.yml, migrations.restart needs to be string
Here was the error I had,

~/nsecbunkerd$ docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.migrations.restart contains an invalid type, it should be a string
dentropy@umbrel:~/nsecbunkerd$ vim docker-compose.yml